harundogdu/twitter-clone

README.md

- git clone https://github.com/xxxx/twitter-clone.git
- The update on who will belong to the xxx field has been passed

fix: fixed git clone section

---

README.md

- How to make prisma build package added to readme

fix: readme updated

---

components/shared/Input.tsx

#15 
- Password display icon has been added so that the user can see the password.

feat: Added password display icon

---

README.md

#27 
- The results of 'npx prisma generate' in the installation area have been fixed.
- Authors listed in alphabetical order

fix: Installing area edited

---

components/modals/LoginModal.tsx
components/modals/RegisterModal.tsx
components/shared/Input.tsx
components/shared/Modal.tsx
utils/helpers.ts

#16 
- Input içindeki verilerin dolu olup olmadığı kontrolü yapılarak buton durumu disabled edildi.
- Input içeriği kontrol edilerek e-mail yapısının istenilen içerikte olmaması durumunda uyarı verilerek buton disabled edildi.

feat: input validations done

---

README.md

- Newly used npm packages added to readme

feat: Built with update

---

components/modals/RegisterModal.tsx
pages/_app.tsx
pages/api/register.ts

#25 
- The entered username is prevented from being the same as other registered usernames.

feat: username is checked

---

pages/api/users/index.ts

feat: "who to follow" section algorithm upgraded

---

components/SidebarItem.tsx
utils/@fake.db.ts

V1.1.0 up/feature/sidebar profile redirect

---

components/users/UserInfo.tsx

feat: when the external urls click, a opening the new page

---

pages/api/users/index.ts

feat: who to follow section algorithm improved and issues well done

---

components/modals/LoginModal.tsx
components/modals/RegisterModal.tsx
components/shared/Input.tsx
pages/api/auth/[...nextauth].ts

#26 
- The user can log in with their email or username.

feat: login with username defined

---

README.md

doc:  readme updated

---

components/Avatar.tsx
components/users/UserHero.tsx

V1.0.0 up/feature/view profile picture

---

pages/users/[username].tsx

fix: correction

---

components/shared/Input.tsx
utils.js

#56 
- The location of the "@" sign has been detailed and the problem has been resolved.

bugfix: General expression arrangement

---

components/users/UserHero.tsx

feat: while viewing image user can close image with click non image area

---

components/Avatar.tsx
components/users/UserHero.tsx
tailwind.config.js
utils/enums.ts

V1.0.0/feature/responsive profile photo

---

components/posts/PostFeeds.tsx

- Loading component was run during page load time.

feat: loading definition inside the page

---

components/SidebarItem.tsx
components/posts/PostFeeds.tsx

V1.0.0/bug fix/profile button

---

components/users/UserHero.tsx

fix: default profile pictures can be view

---

components/PostForm.tsx
package-lock.json
package.json
yarn.lock

#65 
- Up to 80 characters
- Between 80 and 100 characters
- It ends in 100 characters and no more characters can be entered.

feat: Added counter to tweeting forehead

---

components/ActionSidebar.tsx
components/Sidebar.tsx

- Edited according to the sidebar action Twitter application.

fixed: sidebar action renewed

---

components/ActionSidebar.tsx
components/Avatar.tsx
components/posts/PostFeed.tsx

- User can go to profile that who posted via clicking profile photo
- User can go to profile via clicking that users username in actionbar
#88

V1.0.0/bug fix/routing errors

---

components/modals/EditModal.tsx
components/shared/BasicDatePicker.tsx
libs/serverAuth.ts
pages/api/current.ts
pages/api/edit.ts
pages/api/posts/index.ts
pages/api/register.ts
pages/api/users/[username].ts
pages/api/users/index.ts
utils/helpers.ts
yarn.lock

V1.1.0 up/bugfix/user all data display

---

components/modals/EditModal.tsx
components/posts/PostFeed.tsx
components/shared/Input.tsx
components/users/UserInfo.tsx
utils/constants.ts
utils/helpers.ts

V1.1.0 up/feature/external url development

---

pages/404.tsx

#35 
Not: Twitter'ın kendi sitesinde orijinali aşağıda görünen şekildedir. Bana böyle daha okey gibi geldiği için böyle yaptım siz de beğenirseniz böyle kalsın. Beğenilmezse hemen değiştireyim :)

feat: 404 pages styling

---

components/Sidebar.tsx
components/shared/Button.tsx
components/shared/Modal.tsx
pages/404.tsx

- Button componentine eklemeler yapıldı

V1.0.0/feature/page not found

---

components/users/UserHero.tsx

feat: magnification

---

components/Layout.tsx
package.json
tailwind.config.js
yarn.lock

- Scrollbar got new color and size.

feat: scrollbar shaped

---

components/shared/Header.tsx
libs/serverAuth.ts
pages/api/users/[username].ts
pages/users/[username].tsx

V1.1.0 up/feature/twit count development

---

base/button.ts
components/ActionSidebar.tsx
components/PostForm.tsx
components/Sidebar.tsx
components/bottom/Bottom.tsx
components/modals/LoginModal.tsx
components/modals/RegisterModal.tsx
components/modals/TweetModal.tsx
components/shared/Button.tsx
components/shared/Modal.tsx
components/users/UserInfo.tsx
pages/404.tsx
tailwind.config.js

- Button componenti refactor edildi
- Button kullanımları düzeltildi
Yapamadıklarım:
- Base dosyasından değerleri çekemiyorum. (birkaç çözüm yolu denedim ama başaramadım)
-  Margin Vertical/Horizontal , Padding Horizontal/Vertical değerlerini button componenti içinde compile etmiyor. (ya da ben beceremedim :( ) 
Update: hoverlarda da  bir üstteki problem geçerli.

V1.0.0/refactor/button structures

---

components/PostForm.tsx
components/modals/TweetModal.tsx

#91 
- It can continue to write after 100 letters, but it is disabled.
- updated progressbar based on letter count.

feat: renewed progressbar

---

components/ActionSidebar.tsx
components/shared/Header.tsx
pages/404.tsx
pages/api/users/index.ts
pages/connect.tsx

- defined a field where we can find all users

V1.0.0/feature/connect section

---

components/posts/PostFeed.tsx
components/users/UserHero.tsx
pages/404.tsx
tailwind.config.js

#128 
- Şuanda buradaki hiçbir fonksiyon çalışmıyor 
- Seçenekler neleri kullanırız neleri kullanmayız diye düşünüp eklendi, dahasını istek üzerine eklerim.

V1.0.0/feature/post edit

---

components/ActionSidebar.tsx
components/modals/LoginModal.tsx
components/posts/PostFeed.tsx
hooks/useFollow.ts

#134 
- 
- Added footer to sidebar area, linked to transport links.

V1.0.0/feature/action sidebar footer

---

components/posts/PostFeeds.tsx

#90 
- While the user's posts are being loaded, they are greeted with a loading icon.

feat: loading status on user posts

---

README.md
components/ActionSidebar.tsx
components/modals/RegisterModal.tsx
components/posts/PostFeeds.tsx
pages/connect.tsx

V1.0.0/feature/readme update

---

components/ActionSidebar.tsx
components/modals/RegisterModal.tsx
components/posts/PostFeeds.tsx
pages/connect.tsx

#137 
- General arrangements have been made.

V1.0.0/bugfix/general arrangement

---

components/shared/Header.tsx
pages/api/users/[username].ts
yarn.lock

Error in follower count

---

components/shared/Header.tsx
pages/api/users/[username].ts
yarn.lock

Error count display 

---

components/ActionSidebar.tsx
components/Searchbar.tsx
components/WhoToFollow.tsx

feat: sticky

---

components/WhoToFollow.tsx

feat: footer format editing

---

components/PostForm.tsx
components/posts/CommentFeed.tsx
components/posts/CommentItem.tsx
components/posts/PostFeed.tsx
hooks/usePost.ts
pages/api/comments.ts
pages/api/posts/[postId].ts
pages/posts/[postId].tsx
prisma/schema.prisma

feat: comment development

---

components/PostForm.tsx
components/posts/CommentFeed.tsx
components/posts/CommentItem.tsx
components/posts/PostFeed.tsx
hooks/usePost.ts
pages/api/comments.ts
pages/api/posts/[postId].ts
pages/posts/[postId].tsx
prisma/schema.prisma

Comment development
